Task 1
ViktorVoitovich/nodejs pull request #1
Opened 2021-03-15 15:02 UTC by ViktorVoitovich

2021-03-17 13:55 UTC, AliakseiBychyk requested changes

2021-03-17 13:55 UTC, AliakseiBychyk commented on babel.config.json
> +{
Please rename file into `.babelrc` , such convention is used for configuration json files.

2021-03-17 13:55 UTC, AliakseiBychyk commented on package.json
> +    "task2": "nodemon --exec babel-node src/task2.js"
In order to get better evaluation, please implement additionally the same functionality not using babel at all. For example you may have such scripts:
`"task1": "nodemon src/task1.js"`
`"task1:babel": "nodemon -e babel-node src/task1babel.js"`

2021-03-17 13:55 UTC, AliakseiBychyk commented on src/task2.js
> +    fs.createReadStream(csvFilePath),
Please, implement that functionality also using `readFile` `writeFile` methods in the separate file and create separate script in the `package.json`

2021-03-20 08:39 UTC, ViktorVoitovich commented on babel.config.json
> +{
@AliakseiBychyk done

2021-03-20 08:39 UTC, ViktorVoitovich commented on package.json
> +    "task2": "nodemon --exec babel-node src/task2.js"
@AliakseiBychyk done

2021-03-20 08:39 UTC, ViktorVoitovich commented on src/task2.js
> +    fs.createReadStream(csvFilePath),
@AliakseiBychyk done

2021-03-22 07:45 UTC, AliakseiBychyk approved these changes

2021-04-01 05:03 UTC, merged